### ISSUE TITLE
Issue with Craft 3.6.0 > 3.6.10?

### ISSUE THREAD

**Issue by rjgux** [vaersaagod/dospaces#22] opened 2021-03-25 10:46 UTC
I think this *was* an issue with Craft rather than the dospaces plugin, but this may help someone.

Discovered a strange bug when running this plugin on a site using Craft version `3.6.10`. All of our volumes were broken, so we couldn't access or upload assets. Trying to upload a file gave us this error -

```
Upload failed. The error message was: “Error executing "ListObjects" on "mutualcdn.https://ams3.digitaloceanspaces.com"; AWS HTTP error: cURL error 1: Protocol "mutualcdn.https" not supported or disabled in libcurl (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for mutualcdn.https://ams3.digitaloceanspaces.com”
```

The plugin settings were still the same. It was somehow getting confused about the `Endpoint` to use, and prefixing it with the `Bucket` value.

After updating Craft to `3.6.11.1` (latest version) it fixed this issue.

**Comment by jtaccinelli** [comment] 2021-03-27 09:04
I'm also having this issue, but updating hasn't resolved it. Is there any solution to this aside from just updating that seemed to help?

**Comment by mmikkel** [comment] 2021-03-29 10:48
Looks like a duplicate of #21.

**Closed as completed by mmikkel** 2021-03-29 10:48 UTC
